# Generated by Django 3.0.4 on 2020-05-27 22:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_staffverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=50)),
                ('from_date', models.DateField(default=datetime.date.today)),
                ('to_date', models.DateField(default=datetime.date.today)),
                ('reason', models.TextField(max_length=400)),
                ('status', models.CharField(blank=True, default=(('AP', 'Approved'), ('DE', 'Denied')), max_length=12, null=True)),
                ('leave_processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_processor', to='users.Staff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Staff')),
            ],
        ),
    ]
