# Generated by Django 3.0.4 on 2020-04-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
