# Generated by Django 3.0.4 on 2020-04-15 21:20

from django.db import migrations


def create_transcript_attrs(apps,schema_editor):
    TranscriptAttribute = apps.get_model('activities', 'TranscriptAttribute')
    db_alias = schema_editor.connection.alias

    TranscriptAttribute.objects.using(db_alias).bulk_create([
        TranscriptAttribute(transcript_type='Within Nigeria', amount=5000.00),
        TranscriptAttribute(transcript_type='Within Africa', amount=15000.00),
        TranscriptAttribute(transcript_type='International', amount=20000.00),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_transcript_attrs, migrations.RunPython.noop)
    ]
