# Generated by Django 3.0.4 on 2020-04-15 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_trans_attr_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.Request'),
        ),
    ]
