# Generated by Django 3.0.4 on 2020-04-18 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20200415_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcript',
            options={'permissions': [('change_status', 'can change the status of a request to accept or rejected')]},
        ),
    ]
