# Generated by Django 3.0.4 on 2020-04-25 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_staffverification'),
        ('activities', '0005_transcript_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10)),
                ('reason', models.CharField(blank=True, max_length=160, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Request')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Staff')),
            ],
        ),
    ]
