# Generated by Django 3.0.4 on 2020-05-27 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_transcript_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
