# Generated by Django 3.0.4 on 2020-06-18 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_staffverification'),
        ('activities', '0008_delete_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10)),
                ('reason', models.CharField(blank=True, max_length=160, null=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Staff')),
            ],
        ),
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='request',
        ),
        migrations.AddField(
            model_name='transcript',
            name='request_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.AddField(
            model_name='transcriptnote',
            name='transcript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Transcript'),
        ),
    ]
