# Generated by Django 3.0.4 on 2020-03-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_auto_20200315_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('leave', 'Leave'), ('transcripts', 'Transcripts')], default=(('leave', 'Leave'), ('transcripts', 'Transcripts')), max_length=18),
        ),
    ]
